"""AWS adapters: bounded, read-back-verified access to AWS services."""

from ..errors import (
    AbsentResourceError,
    MutationVerificationError,
    ReadError,
    ValidationError,
    WaiterTimeoutError,
)
from .cloudfront import create_invalidation, get_distribution
from .context import (
    AwsContext,
    client_for,
    identity_preflight,
    require_environment,
    session_for,
)
from .ecr import (
    batch_get_image_digests,
    get_lifecycle_policy,
    get_lifecycle_policy_preview,
    list_images,
    put_image,
    put_lifecycle_policy,
    repository_digest,
    start_lifecycle_policy_preview,
)
from .ecs import (
    delete_task_definition,
    deregister_task_definition,
    describe_services,
    describe_task_definition,
    primary_deployment,
    register_task_definition,
    replace_container_images,
    running_digests,
    sanitize_task_definition,
    scale_service,
    service_deployment,
    task_definition_images,
    update_service,
    wait_for_deployment,
    wait_for_running_digests,
    wait_for_service_running_count,
    wait_for_tasks_stopped,
)
from .elb import describe_load_balancer, describe_target_health, load_balancer_dns_name
from .rds import (
    add_tags_to_resource,
    db_instance_arn,
    describe_db_instance,
    list_tags_for_resource,
    remove_tags_from_resource,
    start_db_instance,
    stop_db_instance,
)
from .readback import absent_or_read, mutate_and_read_back
from .s3 import get_object_sha256, list_objects, object_exists, put_object
from .secrets import secret_reference
from .waiters import ThrottlingError, bounded_waiter, with_retry

__all__ = [
    "AbsentResourceError",
    "AwsContext",
    "MutationVerificationError",
    "ReadError",
    "ThrottlingError",
    "ValidationError",
    "WaiterTimeoutError",
    "absent_or_read",
    "add_tags_to_resource",
    "batch_get_image_digests",
    "bounded_waiter",
    "client_for",
    "create_invalidation",
    "db_instance_arn",
    "delete_task_definition",
    "deregister_task_definition",
    "describe_db_instance",
    "describe_load_balancer",
    "describe_services",
    "describe_target_health",
    "describe_task_definition",
    "get_distribution",
    "get_lifecycle_policy",
    "get_lifecycle_policy_preview",
    "get_object_sha256",
    "identity_preflight",
    "list_images",
    "list_objects",
    "list_tags_for_resource",
    "load_balancer_dns_name",
    "mutate_and_read_back",
    "object_exists",
    "primary_deployment",
    "put_image",
    "put_lifecycle_policy",
    "put_object",
    "register_task_definition",
    "remove_tags_from_resource",
    "replace_container_images",
    "repository_digest",
    "require_environment",
    "running_digests",
    "sanitize_task_definition",
    "scale_service",
    "secret_reference",
    "service_deployment",
    "session_for",
    "start_db_instance",
    "start_lifecycle_policy_preview",
    "stop_db_instance",
    "task_definition_images",
    "update_service",
    "wait_for_deployment",
    "wait_for_running_digests",
    "wait_for_service_running_count",
    "wait_for_tasks_stopped",
    "with_retry",
]
