"""Delivery record models: candidate, staging, snapshot, release, rollback, evidence."""

from .candidate import (
    CandidateArtifacts,
    CandidateManifest,
    CandidateTests,
    FrontendArtifact,
    ItemsArtifact,
)
from .common import ArtifactRef, Build, PositiveInt, Source, StrictRecord, UtcDateTime
from .evidence import EvidenceRecord, ExpectedObserved, FailureInfo, PhaseLog, evidence_for_failure
from .promotion import (
    ApprovalEvidenceFile,
    FinalizationReport,
    FinalizationStep,
    FrontendPublishRecord,
    PreflightCandidateIdentity,
    PreflightReport,
    PreflightSnapshotSummary,
    PreflightStagingGate,
    RollbackWindowEntry,
    VerificationJourney,
    VerificationReport,
)
from .recovery import ComponentRecovery, RecoveryResult
from .release import (
    ApprovalEvidence,
    ProductionVerification,
    ReleaseArtifacts,
    ReleaseFrontend,
    ReleaseManifest,
    ReleaseSource,
    SbomAsset,
    SbomSet,
    StagingEvidence,
)
from .retention import (
    RetentionApplyRepo,
    RetentionApplyReport,
    RetentionAuditEntry,
    RetentionAuditFailure,
    RetentionAuditReport,
    RetentionPreviewRepo,
    RetentionPreviewReport,
)
from .rollback import RollbackResult
from .snapshot import FrontendObservation, ProductionSnapshot, ReleaseIdentity, ServiceObservation
from .staging import (
    CleanupConclusion,
    CompatibilityConclusion,
    DatabaseConclusions,
    DiagnosticsRecord,
    E2EConclusion,
    ExpectedArtifacts,
    JourneyConclusion,
    ObservedArtifacts,
    OwnershipMarker,
    Phase,
    ReconcileRecord,
    StagingCandidateIdentity,
    StagingOperationRecord,
)

__all__ = [
    "ApprovalEvidence",
    "ApprovalEvidenceFile",
    "ArtifactRef",
    "Build",
    "CandidateArtifacts",
    "CandidateManifest",
    "CandidateTests",
    "CleanupConclusion",
    "CompatibilityConclusion",
    "ComponentRecovery",
    "DatabaseConclusions",
    "DiagnosticsRecord",
    "E2EConclusion",
    "EvidenceRecord",
    "ExpectedArtifacts",
    "ExpectedObserved",
    "FailureInfo",
    "FinalizationReport",
    "FinalizationStep",
    "FrontendArtifact",
    "FrontendObservation",
    "FrontendPublishRecord",
    "ItemsArtifact",
    "JourneyConclusion",
    "ObservedArtifacts",
    "OwnershipMarker",
    "Phase",
    "PhaseLog",
    "PositiveInt",
    "PreflightCandidateIdentity",
    "PreflightReport",
    "PreflightSnapshotSummary",
    "PreflightStagingGate",
    "ProductionSnapshot",
    "ProductionVerification",
    "ReconcileRecord",
    "RecoveryResult",
    "ReleaseArtifacts",
    "ReleaseFrontend",
    "ReleaseIdentity",
    "ReleaseManifest",
    "ReleaseSource",
    "RetentionApplyRepo",
    "RetentionApplyReport",
    "RetentionAuditEntry",
    "RetentionAuditFailure",
    "RetentionAuditReport",
    "RetentionPreviewRepo",
    "RetentionPreviewReport",
    "RollbackResult",
    "RollbackWindowEntry",
    "SbomAsset",
    "SbomSet",
    "ServiceObservation",
    "Source",
    "StagingCandidateIdentity",
    "StagingEvidence",
    "StagingOperationRecord",
    "StrictRecord",
    "UtcDateTime",
    "VerificationJourney",
    "VerificationReport",
    "evidence_for_failure",
]
